name: Build and deploy a container to an Azure Web App

# In our case image name and web app name are identical 
# so we dont need to redefine a new value to be used in workflow
env:
  IMAGE_NAME: joke-generator
on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{secrets.REGISTRY}}
          username: ${{secrets.DOCKER_ID}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{secrets.AZURE_REGISTRY}}/${{ env.IMAGE_NAME}}:${{ github.sha }}
          file: ./Dockerfile
